apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-exercise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server-exercise
  template:
    metadata:
      labels:
        app: api-server-exercise
    spec:
      containers:
        - name: api-server-exercise
          image: apiserverexercise.azurecr.io/server:latest
          command: ["/APIServerExercise"]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-exercise
spec:
  ports:
    - port: 8080
  selector:
    app: api-server-exercise
  type: LoadBalancer